version: "2"
run:
  concurrency: 4
  modules-download-mode: mod
  issues-exit-code: 0
  allow-parallel-runners: false
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupword
    - errorlint
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - inamedparam
    - lll
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testpackage
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl
  disable:
    - depguard
    - dupl
    - interfacebloat
    - mnd
    - nlreturn
    - wrapcheck
  settings:
    cyclop:
      max-complexity: 15
      package-average: 0
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - cyclop
        path: (.+)_test\.go
    paths:
      - vendor
      - deps
      - META-INF
      - devops
      - proxy
      - third_party$
      - builtin$
      - examples$
severity:
  default: info
  rules:
    - linters:
        - gofmt
        - prealloc
        - predeclared
        - staticcheck
      severity: warning
    - linters:
        - govet
        - nakedret
      severity: warning
    - linters:
        - bodyclose
        - errcheck
        - nilerr
      severity: error
    - linters:
        - asciicheck
        - cyclop
        - deadcode
        - dogsled
        - dupl
        - errorlint
        - exportloopref
        - funlen
        - gci
        - gochecknoglobals
        - gochecknoinits
        - gocognit
        - goconst
        - gocritic
        - gocyclo
        - godot
        - godox
        - gofumpt
        - goimports
        - gomoddirectives
        - goprintffuncname
        - gosec
        - ifshort
        - importas
        - ineffassign
        - lll
        - makezero
        - misspell
        - mnd
        - nestif
        - nlreturn
        - paralleltest
        - promlinter
        - revive
        - rowserrcheck
        - scopelint
        - sqlclosecheck
        - staticcheck
        - structcheck
        - tagliatelle
        - testpackage
        - unconvert
        - unparam
        - unused
        - varcheck
        - wastedassign
        - whitespace
        - wrapcheck
        - wsl
      severity: notice
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - vendor
      - deps
      - META-INF
      - devops
      - proxy
      - third_party$
      - builtin$
      - examples$
